var hierarchy =
[
    [ "HamstarHelpers.Services.AnimatedColor.AnimatedColors", "class_hamstar_helpers_1_1_services_1_1_animated_color_1_1_animated_colors.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Extensions.ArrayExtensions", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_extensions_1_1_array_extensions.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Extensions.BinaryReaderExtensions", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_extensions_1_1_binary_reader_extensions.html", null ],
    [ "HamstarHelpers.Services.GameData.BossDataEntry", "class_hamstar_helpers_1_1_services_1_1_game_data_1_1_boss_data_entry.html", null ],
    [ "HamstarHelpers.Helpers.Buffs.BuffHelpers", "class_hamstar_helpers_1_1_helpers_1_1_buffs_1_1_buff_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Buffs.BuffIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_buffs_1_1_buff_identity_helpers.html", null ],
    [ "HamstarHelpers.Services.Tml.BuildPropertiesViewer", "class_hamstar_helpers_1_1_services_1_1_tml_1_1_build_properties_viewer.html", null ],
    [ "HamstarHelpers.Tiles.CoalTile", "class_hamstar_helpers_1_1_tiles_1_1_coal_tile.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Commands.CommandsHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_commands_1_1_commands_helpers.html", null ],
    [ "HamstarHelpers.Components.Config.ConfigurationDataBase", "class_hamstar_helpers_1_1_components_1_1_config_1_1_configuration_data_base.html", [
      [ "HamstarHelpers.HamstarHelpersConfigData", "class_hamstar_helpers_1_1_hamstar_helpers_config_data.html", null ]
    ] ],
    [ "HamstarHelpers.Services.UI.ControlPanel.ControlPanelTabs", "class_hamstar_helpers_1_1_services_1_1_u_i_1_1_control_panel_1_1_control_panel_tabs.html", null ],
    [ "HamstarHelpers.Services.Debug.CustomHotkeys.CustomHotkeys", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_custom_hotkeys_1_1_custom_hotkeys.html", null ],
    [ "HamstarHelpers.Services.Debug.DataDumper.DataDumper", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_data_dumper_1_1_data_dumper.html", null ],
    [ "HamstarHelpers.Helpers.Misc.DataFileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_data_file_helpers.html", null ],
    [ "HamstarHelpers.Services.DataStore.DataStore", "class_hamstar_helpers_1_1_services_1_1_data_store_1_1_data_store.html", null ],
    [ "HamstarHelpers.Helpers.Debug.DebugHelpers", "class_hamstar_helpers_1_1_helpers_1_1_debug_1_1_debug_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Extensions.DictionaryExtensions", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_extensions_1_1_dictionary_extensions.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.DotNetHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_dot_net_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Dusts.DustHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dusts_1_1_dust_helpers.html", null ],
    [ "HamstarHelpers.Services.Debug.EntityData.EntityData", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_entity_data_1_1_entity_data.html", null ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroups", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_groups.html", null ],
    [ "HamstarHelpers.Helpers.Entities.EntityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_entities_1_1_entity_helpers.html", null ],
    [ "HamstarHelpers.Services.Hooks.ExtendedHooks.ExtendedPlayerHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks_1_1_extended_player_hooks.html", null ],
    [ "HamstarHelpers.Services.ModCompatibilities.ExtensibleInventoryCompat.ExtensibleInventoryCompatibilities", "class_hamstar_helpers_1_1_services_1_1_mod_compatibilities_1_1_extensible_inventory_compat_1_1_e3807db3241c8b751a61d191fea54a5be.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.FileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Info.FormattedGameInfoHelpers", "class_hamstar_helpers_1_1_helpers_1_1_info_1_1_formatted_game_info_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Info.GameInfoHelpers", "class_hamstar_helpers_1_1_helpers_1_1_info_1_1_game_info_helpers.html", null ],
    [ "HamstarHelpers.Components.Errors.HamstarException", "class_hamstar_helpers_1_1_components_1_1_errors_1_1_hamstar_exception.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Encoding.HashHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_encoding_1_1_hash_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDHealthBarHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_health_bar_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDMapHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_map_helpers.html", null ],
    [ "HamstarHelpers.Services.Messages.InboxMessages", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_inbox_messages.html", null ],
    [ "HamstarHelpers.Helpers.Items.Attributes.ItemAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_attributes_1_1_item_attribute_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.Attributes.ItemRarityAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_attributes_1_1_item_rarity_attribute_helpers.html", null ],
    [ "HamstarHelpers.Components.Config.JsonConfig< HamstarHelpers.HamstarHelpersConfigData >", "class_hamstar_helpers_1_1_components_1_1_config_1_1_json_config.html", null ],
    [ "HamstarHelpers.Components.Config.JsonConfigBase", "class_hamstar_helpers_1_1_components_1_1_config_1_1_json_config_base.html", [
      [ "HamstarHelpers.Components.Config.JsonConfig< T >", "class_hamstar_helpers_1_1_components_1_1_config_1_1_json_config.html", null ]
    ] ],
    [ "HamstarHelpers.Helpers.DotNET.LINQHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_l_i_n_q_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.LoadHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_load_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Debug.LogHelpers", "class_hamstar_helpers_1_1_helpers_1_1_debug_1_1_log_helpers.html", null ],
    [ "HamstarHelpers.Items.MagiTechScrapItem", "class_hamstar_helpers_1_1_items_1_1_magi_tech_scrap_item.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Menus.MainMenuHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_menus_1_1_main_menu_helpers.html", null ],
    [ "HamstarHelpers.Services.UI.Menus.MenuContextService", "class_hamstar_helpers_1_1_services_1_1_u_i_1_1_menus_1_1_menu_context_service.html", null ],
    [ "HamstarHelpers.Helpers.Misc.MiscHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_misc_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModBoilerplateHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_boilerplate_helpers.html", null ],
    [ "HamstarHelpers.Helpers.ModHelpers.ModFeaturesHelpers", "class_hamstar_helpers_1_1_helpers_1_1_mod_helpers_1_1_mod_features_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModListHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_list_helpers.html", null ],
    [ "HamstarHelpers.Services.ModHelpers.ModLockService", "class_hamstar_helpers_1_1_services_1_1_mod_helpers_1_1_mod_lock_service.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Menus.ModMenuHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_menus_1_1_mod_menu_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.MusicBoxHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_music_box_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Misc.MusicHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_music_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Net.NetPlayHelpers", "class_hamstar_helpers_1_1_helpers_1_1_net_1_1_net_play_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCBannerHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_banner_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCDrawHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_draw_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCGroupIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_group_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCInvasionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_invasion_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCTownHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_town_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Reflection.NullableAttribute", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_reflection_1_1_nullable_attribute.html", null ],
    [ "HamstarHelpers.Helpers.Misc.PaintHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_paint_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerFileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerHeadDrawHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_head_draw_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerItemFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_item_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerItemHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_item_helpers.html", null ],
    [ "HamstarHelpers.Services.Messages.PlayerLabelText", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_player_label_text.html", null ],
    [ "HamstarHelpers.Services.Messages.PlayerMessages", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_player_messages.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerModHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_mod_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerMovementHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_movement_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerNPCHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_n_p_c_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerTeamHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_team_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerWarpHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_warp_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Projectiles.ProjectileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_projectile_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Projectiles.ProjectileIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_projectile_identity_helpers.html", null ],
    [ "HamstarHelpers.Services.PromisedHooks.PromisedHooks", "class_hamstar_helpers_1_1_services_1_1_promised_hooks_1_1_promised_hooks.html", null ],
    [ "HamstarHelpers.Components.Network.ProtocolIgnoreAttribute", "class_hamstar_helpers_1_1_components_1_1_network_1_1_protocol_ignore_attribute.html", null ],
    [ "HamstarHelpers.Components.Network.ProtocolWriteIgnoreClientAttribute", "class_hamstar_helpers_1_1_components_1_1_network_1_1_protocol_write_ignore_client_attribute.html", null ],
    [ "HamstarHelpers.Components.Network.ProtocolWriteIgnoreServerAttribute", "class_hamstar_helpers_1_1_components_1_1_network_1_1_protocol_write_ignore_server_attribute.html", null ],
    [ "HamstarHelpers.Components.DataStructures.ReadOnlyDictionaryOfSets< K, V >", "class_hamstar_helpers_1_1_components_1_1_data_structures_1_1_read_only_dictionary_of_sets.html", null ],
    [ "HamstarHelpers.Components.DataStructures.ReadOnlyDictionaryOfSets< string, int >", "class_hamstar_helpers_1_1_components_1_1_data_structures_1_1_read_only_dictionary_of_sets.html", null ],
    [ "HamstarHelpers.Components.DataStructures.ReadOnlySet< T >", "class_hamstar_helpers_1_1_components_1_1_data_structures_1_1_read_only_set.html", null ],
    [ "HamstarHelpers.Components.DataStructures.ReadOnlySet< int >", "class_hamstar_helpers_1_1_components_1_1_data_structures_1_1_read_only_set.html", null ],
    [ "HamstarHelpers.Helpers.Recipes.RecipeGroupHelpers", "class_hamstar_helpers_1_1_helpers_1_1_recipes_1_1_recipe_group_helpers.html", null ],
    [ "HamstarHelpers.Services.RecipeHack.RecipeHack", "class_hamstar_helpers_1_1_services_1_1_recipe_hack_1_1_recipe_hack.html", null ],
    [ "HamstarHelpers.Helpers.Recipes.RecipeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_recipes_1_1_recipe_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Recipes.RecipeIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_recipes_1_1_recipe_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Reflection.ReflectionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_reflection_1_1_reflection_helpers.html", null ],
    [ "HamstarHelpers.Services.Server.Server", "class_hamstar_helpers_1_1_services_1_1_server_1_1_server.html", null ],
    [ "HamstarHelpers.Services.Messages.SimpleMessage", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_simple_message.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Encoding.SimpleStringCipher", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_encoding_1_1_simple_string_cipher.html", null ],
    [ "HamstarHelpers.Helpers.Steam.SteamHelpers", "class_hamstar_helpers_1_1_helpers_1_1_steam_1_1_steam_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.StreamHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_stream_helpers.html", null ],
    [ "HamstarHelpers.Components.Protocol.Stream.StreamProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_stream_1_1_stream_protocol.html", [
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", [
        [ "HamstarHelpers.Components.Protocol.Packet.Interfaces.PacketProtocolRequestToClient", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_interfaces_1_1_packet_protocol_request_to_client.html", null ],
        [ "HamstarHelpers.Components.Protocol.Packet.Interfaces.PacketProtocolRequestToServer", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_interfaces_1_1_packet_protocol_request_to_server.html", null ],
        [ "HamstarHelpers.Components.Protocol.Packet.Interfaces.PacketProtocolSendToClient", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_interfaces_1_1_packet_protocol_send_to_client.html", null ],
        [ "HamstarHelpers.Components.Protocol.Packet.Interfaces.PacketProtocolSendToServer", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_interfaces_1_1_packet_protocol_send_to_server.html", null ],
        [ "HamstarHelpers.Components.Protocol.Packet.Interfaces.PacketProtocolSentToEither", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_interfaces_1_1_packet_protocol_sent_to_either.html", null ],
        [ "HamstarHelpers.Components.Protocol.Packet.Interfaces.PacketProtocolSyncClient", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_interfaces_1_1_packet_protocol_sync_client.html", null ]
      ] ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Components.Protocol.Packet.PacketProtocol", "class_hamstar_helpers_1_1_components_1_1_protocol_1_1_packet_1_1_packet_protocol.html", null ]
    ] ],
    [ "HamstarHelpers.Helpers.DotNET.Formatting.StringFormattingHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_formatting_1_1_string_formatting_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.SystemHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_system_helpers.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.TextInputEventArgs", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_text_input_event_args.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileBiomeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_biome_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileType", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_type.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileWallHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_wall_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileWorldHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_world_helpers.html", null ],
    [ "HamstarHelpers.Services.Timers.Timers", "class_hamstar_helpers_1_1_services_1_1_timers_1_1_timers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.TmlHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_tml_helpers.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UICheckbox", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_checkbox.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UIDialog", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_dialog.html", [
      [ "HamstarHelpers.Components.UI.Elements.Dialogs.UIPromptDialog", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_dialogs_1_1_u_i_prompt_dialog.html", null ]
    ] ],
    [ "HamstarHelpers.Helpers.UI.UIHelpers", "class_hamstar_helpers_1_1_helpers_1_1_u_i_1_1_u_i_helpers.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UIHiddenPanel", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_hidden_panel.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UIModData", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_mod_data.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.Dialogs.UIPromptPanel", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_dialogs_1_1_u_i_prompt_panel.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UITextArea", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_text_area.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UITextField", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_text_field.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UITextPanelButton", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_text_panel_button.html", null ],
    [ "HamstarHelpers.Components.UI.UITheme", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_u_i_theme.html", null ],
    [ "HamstarHelpers.Components.UI.Elements.UIWebUrl", "class_hamstar_helpers_1_1_components_1_1_u_i_1_1_elements_1_1_u_i_web_url.html", null ],
    [ "HamstarHelpers.Helpers.User.UserHelpers", "class_hamstar_helpers_1_1_helpers_1_1_user_1_1_user_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Net.WebConnectionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_net_1_1_web_connection_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Net.WebHelpers", "class_hamstar_helpers_1_1_helpers_1_1_net_1_1_web_helpers.html", null ],
    [ "HamstarHelpers.Components.DataStructures.WorldDictionary< T >", "class_hamstar_helpers_1_1_components_1_1_data_structures_1_1_world_dictionary.html", null ],
    [ "HamstarHelpers.Helpers.World.WorldFileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_world_1_1_world_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.World.WorldHelpers", "class_hamstar_helpers_1_1_helpers_1_1_world_1_1_world_helpers.html", null ],
    [ "HamstarHelpers.Helpers.World.WorldStateHelpers", "class_hamstar_helpers_1_1_helpers_1_1_world_1_1_world_state_helpers.html", null ],
    [ "HamstarHelpers.Helpers.XNA.XNAColorHelpers", "class_hamstar_helpers_1_1_helpers_1_1_x_n_a_1_1_x_n_a_color_helpers.html", null ],
    [ "HamstarHelpers.Components.Protocols.XNAContractResolver", "class_hamstar_helpers_1_1_components_1_1_protocols_1_1_x_n_a_contract_resolver.html", null ],
    [ "HamstarHelpers.Helpers.XNA.XNAHelpers", "class_hamstar_helpers_1_1_helpers_1_1_x_n_a_1_1_x_n_a_helpers.html", null ]
];