var hierarchy =
[
    [ "HamstarHelpers.Services.AnimatedColor.AnimatedColors", "class_hamstar_helpers_1_1_services_1_1_animated_color_1_1_animated_colors.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Extensions.ArrayExtensions", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_extensions_1_1_array_extensions.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.BasicModInfo", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_basic_mod_info.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Extensions.BinaryReaderExtensions", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_extensions_1_1_binary_reader_extensions.html", null ],
    [ "HamstarHelpers.Services.GameData.BossData", "class_hamstar_helpers_1_1_services_1_1_game_data_1_1_boss_data.html", null ],
    [ "HamstarHelpers.Services.GameData.BossDataEntry", "class_hamstar_helpers_1_1_services_1_1_game_data_1_1_boss_data_entry.html", null ],
    [ "HamstarHelpers.Helpers.Buffs.BuffAttributesHelpers", "class_hamstar_helpers_1_1_helpers_1_1_buffs_1_1_buff_attributes_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Buffs.BuffHelpers", "class_hamstar_helpers_1_1_helpers_1_1_buffs_1_1_buff_helpers.html", null ],
    [ "HamstarHelpers.Services.TML.BuildPropertiesViewer", "class_hamstar_helpers_1_1_services_1_1_t_m_l_1_1_build_properties_viewer.html", null ],
    [ "HamstarHelpers.Tiles.CoalTile", "class_hamstar_helpers_1_1_tiles_1_1_coal_tile.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Commands.CommandsHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_commands_1_1_commands_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.ConfigHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_config_helpers.html", null ],
    [ "HamstarHelpers.Services.UI.ControlPanel.ControlPanelTabs", "class_hamstar_helpers_1_1_services_1_1_u_i_1_1_control_panel_1_1_control_panel_tabs.html", null ],
    [ "HamstarHelpers.Services.Debug.CustomHotkeys.CustomHotkeys", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_custom_hotkeys_1_1_custom_hotkeys.html", null ],
    [ "HamstarHelpers.Services.Hooks.LoadHooks.CustomLoadHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_load_hooks_1_1_custom_load_hooks.html", null ],
    [ "HamstarHelpers.Services.Hooks.LoadHooks.CustomLoadHookValidator< T >", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_load_hooks_1_1_custom_load_hook_validator.html", null ],
    [ "HamstarHelpers.Services.Debug.DataDumper.DataDumper", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_data_dumper_1_1_data_dumper.html", null ],
    [ "HamstarHelpers.Services.DataStore.DataStore", "class_hamstar_helpers_1_1_services_1_1_data_store_1_1_data_store.html", null ],
    [ "HamstarHelpers.Helpers.Debug.DebugHelpers", "class_hamstar_helpers_1_1_helpers_1_1_debug_1_1_debug_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Extensions.DictionaryExtensions", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_extensions_1_1_dictionary_extensions.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.DotNetHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_dot_net_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Dusts.DustHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dusts_1_1_dust_helpers.html", null ],
    [ "HamstarHelpers.Services.Debug.EntityData.EntityData", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_entity_data_1_1_entity_data.html", null ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroupDependencies", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_group_dependencies.html", null ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroupMatcher< T >", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_group_matcher.html", null ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroupMatcher< Item >", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_group_matcher.html", [
      [ "HamstarHelpers.Services.EntityGroups.ItemGroupMatcher", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_item_group_matcher.html", null ]
    ] ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroupMatcher< NPC >", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_group_matcher.html", [
      [ "HamstarHelpers.Services.EntityGroups.NPCGroupMatcher", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_n_p_c_group_matcher.html", null ]
    ] ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroupMatcher< Projectile >", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_group_matcher.html", [
      [ "HamstarHelpers.Services.EntityGroups.ProjectileGroupMatcher", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_projectile_group_matcher.html", null ]
    ] ],
    [ "HamstarHelpers.Services.EntityGroups.EntityGroups", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_entity_groups.html", null ],
    [ "HamstarHelpers.Helpers.Entities.EntityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_entities_1_1_entity_helpers.html", null ],
    [ "HamstarHelpers.Services.Hooks.ExtendedHooks.ExtendedPlayerHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks_1_1_extended_player_hooks.html", null ],
    [ "HamstarHelpers.Services.ModCompatibilities.ExtensibleInventoryCompat.ExtensibleInventoryCompatibilities", "class_hamstar_helpers_1_1_services_1_1_mod_compatibilities_1_1_extensible_inventory_compat_1_1_e3807db3241c8b751a61d191fea54a5be.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.FileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Info.FormattedGameInfoHelpers", "class_hamstar_helpers_1_1_helpers_1_1_info_1_1_formatted_game_info_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.FullIntDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_full_int_definition.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.FullPercentFloatDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_full_percent_float_definition.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.FullScreenPercentPositionDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_full_screen_percent_position_definition.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.FullScreenPositionDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_full_screen_position_definition.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.FullSingleDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_full_single_definition.html", null ],
    [ "HamstarHelpers.Helpers.Info.GameInfoHelpers", "class_hamstar_helpers_1_1_helpers_1_1_info_1_1_game_info_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Encoding.HashHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_encoding_1_1_hash_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDElementHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_element_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDHealthBarHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_health_bar_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_helpers.html", null ],
    [ "HamstarHelpers.Helpers.HUD.HUDMapHelpers", "class_hamstar_helpers_1_1_helpers_1_1_h_u_d_1_1_h_u_d_map_helpers.html", null ],
    [ "HamstarHelpers.Services.Messages.Inbox.InboxMessages", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_inbox_1_1_inbox_messages.html", null ],
    [ "HamstarHelpers.Classes.DataStructures.IReadOnlySet< T >", "interface_hamstar_helpers_1_1_classes_1_1_data_structures_1_1_i_read_only_set.html", [
      [ "HamstarHelpers.Classes.DataStructures.ReadOnlySet< T >", "class_hamstar_helpers_1_1_classes_1_1_data_structures_1_1_read_only_set.html", null ]
    ] ],
    [ "HamstarHelpers.Helpers.Items.Attributes.ItemAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_attributes_1_1_item_attribute_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemGroupDefinition", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_group_definition.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemGroupIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_group_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.ItemIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_item_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Items.Attributes.ItemRarityAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_attributes_1_1_item_rarity_attribute_helpers.html", null ],
    [ "HamstarHelpers.Classes.UI.Theme.IThemeable", "interface_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_i_themeable.html", [
      [ "HamstarHelpers.Classes.UI.Elements.UIThemedPanel", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_themed_panel.html", [
        [ "HamstarHelpers.Classes.UI.Elements.Dialogs.UIPromptPanel", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_dialogs_1_1_u_i_prompt_panel.html", null ],
        [ "HamstarHelpers.Classes.UI.Elements.Menu.UIMenuPanel", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_menu_1_1_u_i_menu_panel.html", [
          [ "HamstarHelpers.Classes.UI.Menu.UI.UIInfoDisplay", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_menu_1_1_u_i_1_1_u_i_info_display.html", null ]
        ] ],
        [ "HamstarHelpers.Classes.UI.Elements.UIModData", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_mod_data.html", null ],
        [ "HamstarHelpers.Classes.UI.Elements.UIModData", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_mod_data.html", null ],
        [ "HamstarHelpers.Classes.UI.Elements.UIModData", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_mod_data.html", null ],
        [ "HamstarHelpers.Classes.UI.Elements.UITextArea", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_text_area.html", null ],
        [ "HamstarHelpers.Classes.UI.Elements.UITextField", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_text_field.html", null ]
      ] ],
      [ "HamstarHelpers.Classes.UI.Elements.UIThemedText", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_themed_text.html", [
        [ "HamstarHelpers.Classes.UI.Elements.UICheckbox", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_checkbox.html", null ]
      ] ],
      [ "HamstarHelpers.Classes.UI.Elements.UIThemedTextPanel", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_themed_text_panel.html", [
        [ "HamstarHelpers.Classes.UI.Elements.UITextPanelButton", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_text_panel_button.html", [
          [ "HamstarHelpers.Classes.UI.Elements.Menu.UIMenuButton", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_menu_1_1_u_i_menu_button.html", null ]
        ] ]
      ] ],
      [ "HamstarHelpers.Classes.UI.Theme.UIThemedElement", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_u_i_themed_element.html", [
        [ "HamstarHelpers.Classes.UI.Elements.UIImageUrl", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_image_url.html", null ],
        [ "HamstarHelpers.Classes.UI.Elements.UIWebUrl", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_web_url.html", null ]
      ] ],
      [ "HamstarHelpers.Classes.UI.Theme.UIThemedState", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_u_i_themed_state.html", [
        [ "HamstarHelpers.Classes.UI.Elements.UIDialog", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_dialog.html", [
          [ "HamstarHelpers.Classes.UI.Elements.Dialogs.UIPromptDialog", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_dialogs_1_1_u_i_prompt_dialog.html", null ]
        ] ]
      ] ]
    ] ],
    [ "HamstarHelpers.Helpers.DotNET.LINQHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_l_i_n_q_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.LoadHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_load_helpers.html", null ],
    [ "HamstarHelpers.Services.Hooks.LoadHooks.LoadHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_load_hooks_1_1_load_hooks.html", null ],
    [ "HamstarHelpers.Helpers.Debug.LogHelpers", "class_hamstar_helpers_1_1_helpers_1_1_debug_1_1_log_helpers.html", null ],
    [ "HamstarHelpers.Items.MagiTechScrapItem", "class_hamstar_helpers_1_1_items_1_1_magi_tech_scrap_item.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Menus.MainMenuHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_menus_1_1_main_menu_helpers.html", null ],
    [ "HamstarHelpers.Classes.UI.Menus.MenuContext", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_menus_1_1_menu_context.html", [
      [ "HamstarHelpers.Classes.UI.Menu.SessionMenuContext", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_menu_1_1_session_menu_context.html", null ],
      [ "HamstarHelpers.Classes.UI.Menu.SessionMenuContext", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_menu_1_1_session_menu_context.html", null ],
      [ "HamstarHelpers.Classes.UI.Menus.WidgetMenuContext", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_menus_1_1_widget_menu_context.html", null ]
    ] ],
    [ "HamstarHelpers.Services.UI.Menus.MenuContextService", "class_hamstar_helpers_1_1_services_1_1_u_i_1_1_menus_1_1_menu_context_service.html", null ],
    [ "HamstarHelpers.Classes.UI.Menu.MenuItem", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_menu_1_1_menu_item.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Menus.MenuUIs", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_menus_1_1_menu_u_is.html", null ],
    [ "HamstarHelpers.Helpers.Misc.MiscHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_misc_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModBoilerplateHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_boilerplate_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Misc.ModCustomDataFileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_mod_custom_data_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.ModHelpers.ModFeaturesHelpers", "class_hamstar_helpers_1_1_helpers_1_1_mod_helpers_1_1_mod_features_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_helpers.html", null ],
    [ "HamstarHelpers.ModHelpersConfig", "class_hamstar_helpers_1_1_mod_helpers_config.html", null ],
    [ "HamstarHelpers.Classes.Errors.ModHelpersException", "class_hamstar_helpers_1_1_classes_1_1_errors_1_1_mod_helpers_exception.html", null ],
    [ "HamstarHelpers.ModHelpersPrivilegedUserConfig", "class_hamstar_helpers_1_1_mod_helpers_privileged_user_config.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Mods.ModListHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_mods_1_1_mod_list_helpers.html", null ],
    [ "HamstarHelpers.Services.ModHelpers.ModLockService", "class_hamstar_helpers_1_1_services_1_1_mod_helpers_1_1_mod_lock_service.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Menus.ModMenuHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_menus_1_1_mod_menu_helpers.html", null ],
    [ "HamstarHelpers.Classes.ModTagDefinitions.ModTagDefinition", "class_hamstar_helpers_1_1_classes_1_1_mod_tag_definitions_1_1_mod_tag_definition.html", null ],
    [ "HamstarHelpers.Helpers.Items.MusicBoxHelpers", "class_hamstar_helpers_1_1_helpers_1_1_items_1_1_music_box_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Misc.MusicHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_music_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Net.NetPlayHelpers", "class_hamstar_helpers_1_1_helpers_1_1_net_1_1_net_play_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.Attributes.NPCAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_attributes_1_1_n_p_c_attribute_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCBannerHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_banner_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCDrawHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_draw_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCGroupIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_group_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCInvasionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_invasion_helpers.html", null ],
    [ "HamstarHelpers.Helpers.NPCs.NPCTownHelpers", "class_hamstar_helpers_1_1_helpers_1_1_n_p_cs_1_1_n_p_c_town_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Reflection.NullableAttribute", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_reflection_1_1_nullable_attribute.html", null ],
    [ "HamstarHelpers.Helpers.Misc.PaintHelpers", "class_hamstar_helpers_1_1_helpers_1_1_misc_1_1_paint_helpers.html", null ],
    [ "HamstarHelpers.Helpers.ParticleFx.ParticleFxHelpers", "class_hamstar_helpers_1_1_helpers_1_1_particle_fx_1_1_particle_fx_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.PercentFloatDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_percent_float_definition.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerFileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerHeadDrawHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_head_draw_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerItemFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_item_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerItemHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_item_helpers.html", null ],
    [ "HamstarHelpers.Services.Messages.Player.PlayerLabelText", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_player_1_1_player_label_text.html", null ],
    [ "HamstarHelpers.Services.Messages.Player.PlayerMessages", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_player_1_1_player_messages.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerModHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_mod_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerMovementHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_movement_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerNPCHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_n_p_c_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerTeamHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_team_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Players.PlayerWarpHelpers", "class_hamstar_helpers_1_1_helpers_1_1_players_1_1_player_warp_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.PositiveIntDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_positive_int_definition.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.PositiveSingleDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_positive_single_definition.html", null ],
    [ "HamstarHelpers.Helpers.Projectiles.Attributes.ProjectileAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_attributes_1_1_projectile_attribute_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Projectiles.ProjectileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_projectile_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Projectiles.ProjectileIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_projectile_identity_helpers.html", null ],
    [ "HamstarHelpers.Classes.Protocols.ProtocolIgnoreAttribute", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_protocol_ignore_attribute.html", null ],
    [ "HamstarHelpers.Classes.Protocols.ProtocolWriteIgnoreClientAttribute", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_protocol_write_ignore_client_attribute.html", null ],
    [ "HamstarHelpers.Classes.Protocols.ProtocolWriteIgnoreServerAttribute", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_protocol_write_ignore_server_attribute.html", null ],
    [ "HamstarHelpers.Classes.DataStructures.ReadOnlyDictionaryOfSets< K, V >", "class_hamstar_helpers_1_1_classes_1_1_data_structures_1_1_read_only_dictionary_of_sets.html", null ],
    [ "HamstarHelpers.Classes.DataStructures.ReadOnlyDictionaryOfSets< string, int >", "class_hamstar_helpers_1_1_classes_1_1_data_structures_1_1_read_only_dictionary_of_sets.html", null ],
    [ "HamstarHelpers.Helpers.Recipes.RecipeGroupHelpers", "class_hamstar_helpers_1_1_helpers_1_1_recipes_1_1_recipe_group_helpers.html", null ],
    [ "HamstarHelpers.Services.RecipeHack.RecipeHack", "class_hamstar_helpers_1_1_services_1_1_recipe_hack_1_1_recipe_hack.html", null ],
    [ "HamstarHelpers.Helpers.Recipes.RecipeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_recipes_1_1_recipe_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Recipes.RecipeIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_recipes_1_1_recipe_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Reflection.ReflectionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_reflection_1_1_reflection_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.ScreenPercentPositionDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_screen_percent_position_definition.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.Configs.ScreenPositionDefinition", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_configs_1_1_screen_position_definition.html", null ],
    [ "HamstarHelpers.Services.Server.Server", "class_hamstar_helpers_1_1_services_1_1_server_1_1_server.html", null ],
    [ "HamstarHelpers.Services.Messages.Simple.SimpleMessage", "class_hamstar_helpers_1_1_services_1_1_messages_1_1_simple_1_1_simple_message.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.Encoding.SimpleStringCipher", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_encoding_1_1_simple_string_cipher.html", null ],
    [ "HamstarHelpers.Helpers.Steam.SteamHelpers", "class_hamstar_helpers_1_1_helpers_1_1_steam_1_1_steam_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.StreamHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_stream_helpers.html", null ],
    [ "HamstarHelpers.Classes.Protocols.Stream.StreamProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_stream_1_1_stream_protocol.html", [
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", [
        [ "HamstarHelpers.Classes.Protocols.Packet.Interfaces.PacketProtocolRequestToClient", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_interfaces_1_1_packet_protocol_request_to_client.html", null ],
        [ "HamstarHelpers.Classes.Protocols.Packet.Interfaces.PacketProtocolRequestToServer", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_interfaces_1_1_packet_protocol_request_to_server.html", null ],
        [ "HamstarHelpers.Classes.Protocols.Packet.Interfaces.PacketProtocolSendToClient", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_interfaces_1_1_packet_protocol_send_to_client.html", null ],
        [ "HamstarHelpers.Classes.Protocols.Packet.Interfaces.PacketProtocolSendToServer", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_interfaces_1_1_packet_protocol_send_to_server.html", null ],
        [ "HamstarHelpers.Classes.Protocols.Packet.Interfaces.PacketProtocolSentToEither", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_interfaces_1_1_packet_protocol_sent_to_either.html", null ],
        [ "HamstarHelpers.Classes.Protocols.Packet.Interfaces.PacketProtocolSyncClient", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_interfaces_1_1_packet_protocol_sync_client.html", null ]
      ] ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ],
      [ "HamstarHelpers.Classes.Protocols.Packet.PacketProtocol", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_packet_1_1_packet_protocol.html", null ]
    ] ],
    [ "HamstarHelpers.Helpers.DotNET.Formatting.StringFormattingHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_formatting_1_1_string_formatting_helpers.html", null ],
    [ "HamstarHelpers.Helpers.DotNET.SystemHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_system_helpers.html", null ],
    [ "HamstarHelpers.Classes.UI.Elements.TextInputEventArgs", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_text_input_event_args.html", null ],
    [ "HamstarHelpers.Classes.UI.Theme.ThemedAttrbute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_themed_attrbute.html", [
      [ "HamstarHelpers.Classes.UI.Theme.ButtonThemeAttribute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_button_theme_attribute.html", null ],
      [ "HamstarHelpers.Classes.UI.Theme.InputThemeAttribute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_input_theme_attribute.html", null ],
      [ "HamstarHelpers.Classes.UI.Theme.ListContainerThemeAttribute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_list_container_theme_attribute.html", null ],
      [ "HamstarHelpers.Classes.UI.Theme.ListItemThemeAttribute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_list_item_theme_attribute.html", null ],
      [ "HamstarHelpers.Classes.UI.Theme.PanelThemeAttribute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_panel_theme_attribute.html", null ],
      [ "HamstarHelpers.Classes.UI.Theme.TextThemeAttribute", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_text_theme_attribute.html", null ]
    ] ],
    [ "HamstarHelpers.Helpers.Tiles.TileAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_attribute_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileBiomeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_biome_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Collisions.TileCollisionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_collisions_1_1_tile_collision_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileFinderHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_finder_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_helpers.html", null ],
    [ "HamstarHelpers.Helpers.TileHelpers.TileIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tile_helpers_1_1_tile_identity_helpers.html", null ],
    [ "HamstarHelpers.Classes.Tiles.TilePattern.TilePattern", "class_hamstar_helpers_1_1_classes_1_1_tiles_1_1_tile_pattern_1_1_tile_pattern.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileWallHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_wall_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileWallIdentityHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_wall_identity_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Tiles.TileWorldHelpers", "class_hamstar_helpers_1_1_helpers_1_1_tiles_1_1_tile_world_helpers.html", null ],
    [ "HamstarHelpers.Services.Timers.Timers", "class_hamstar_helpers_1_1_services_1_1_timers_1_1_timers.html", null ],
    [ "HamstarHelpers.Helpers.TModLoader.TmlHelpers", "class_hamstar_helpers_1_1_helpers_1_1_t_mod_loader_1_1_tml_helpers.html", null ],
    [ "HamstarHelpers.Helpers.UI.UIHelpers", "class_hamstar_helpers_1_1_helpers_1_1_u_i_1_1_u_i_helpers.html", null ],
    [ "HamstarHelpers.Classes.UI.Elements.UIHiddenPanel", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_elements_1_1_u_i_hidden_panel.html", null ],
    [ "HamstarHelpers.Classes.UI.Theme.UITheme", "class_hamstar_helpers_1_1_classes_1_1_u_i_1_1_theme_1_1_u_i_theme.html", null ],
    [ "HamstarHelpers.Helpers.User.UserHelpers", "class_hamstar_helpers_1_1_helpers_1_1_user_1_1_user_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Net.WebConnectionHelpers", "class_hamstar_helpers_1_1_helpers_1_1_net_1_1_web_connection_helpers.html", null ],
    [ "HamstarHelpers.Helpers.Net.WebHelpers", "class_hamstar_helpers_1_1_helpers_1_1_net_1_1_web_helpers.html", null ],
    [ "HamstarHelpers.Classes.DataStructures.WorldDictionary< T >", "class_hamstar_helpers_1_1_classes_1_1_data_structures_1_1_world_dictionary.html", null ],
    [ "HamstarHelpers.Helpers.World.WorldFileHelpers", "class_hamstar_helpers_1_1_helpers_1_1_world_1_1_world_file_helpers.html", null ],
    [ "HamstarHelpers.Helpers.World.WorldHelpers", "class_hamstar_helpers_1_1_helpers_1_1_world_1_1_world_helpers.html", null ],
    [ "HamstarHelpers.Helpers.World.WorldStateHelpers", "class_hamstar_helpers_1_1_helpers_1_1_world_1_1_world_state_helpers.html", null ],
    [ "HamstarHelpers.Services.Hooks.WorldHooks.WorldTimeHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_world_hooks_1_1_world_time_hooks.html", null ],
    [ "HamstarHelpers.Helpers.XNA.XNAColorHelpers", "class_hamstar_helpers_1_1_helpers_1_1_x_n_a_1_1_x_n_a_color_helpers.html", null ],
    [ "HamstarHelpers.Classes.Protocols.XNAContractResolver", "class_hamstar_helpers_1_1_classes_1_1_protocols_1_1_x_n_a_contract_resolver.html", null ],
    [ "HamstarHelpers.Helpers.XNA.XNAHelpers", "class_hamstar_helpers_1_1_helpers_1_1_x_n_a_1_1_x_n_a_helpers.html", null ]
];