var namespace_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks =
[
    [ "ExtendedPlayerHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks_1_1_extended_player_hooks.html", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks_1_1_extended_player_hooks" ],
    [ "ExtendedTileHooks", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks_1_1_extended_tile_hooks.html", "class_hamstar_helpers_1_1_services_1_1_hooks_1_1_extended_hooks_1_1_extended_tile_hooks" ]
];