var namespace_hamstar_helpers_1_1_services =
[
    [ "AnimatedColor", "namespace_hamstar_helpers_1_1_services_1_1_animated_color.html", "namespace_hamstar_helpers_1_1_services_1_1_animated_color" ],
    [ "AnimatedTexture", "namespace_hamstar_helpers_1_1_services_1_1_animated_texture.html", "namespace_hamstar_helpers_1_1_services_1_1_animated_texture" ],
    [ "Camera", "namespace_hamstar_helpers_1_1_services_1_1_camera.html", "namespace_hamstar_helpers_1_1_services_1_1_camera" ],
    [ "Cheats", "namespace_hamstar_helpers_1_1_services_1_1_cheats.html", "namespace_hamstar_helpers_1_1_services_1_1_cheats" ],
    [ "Configs", "namespace_hamstar_helpers_1_1_services_1_1_configs.html", "namespace_hamstar_helpers_1_1_services_1_1_configs" ],
    [ "DataStore", "namespace_hamstar_helpers_1_1_services_1_1_data_store.html", "namespace_hamstar_helpers_1_1_services_1_1_data_store" ],
    [ "Debug", "namespace_hamstar_helpers_1_1_services_1_1_debug.html", "namespace_hamstar_helpers_1_1_services_1_1_debug" ],
    [ "Dialogue", "namespace_hamstar_helpers_1_1_services_1_1_dialogue.html", "namespace_hamstar_helpers_1_1_services_1_1_dialogue" ],
    [ "EntityControls", "namespace_hamstar_helpers_1_1_services_1_1_entity_controls.html", "namespace_hamstar_helpers_1_1_services_1_1_entity_controls" ],
    [ "EntityGroups", "namespace_hamstar_helpers_1_1_services_1_1_entity_groups.html", "namespace_hamstar_helpers_1_1_services_1_1_entity_groups" ],
    [ "Hooks", "namespace_hamstar_helpers_1_1_services_1_1_hooks.html", "namespace_hamstar_helpers_1_1_services_1_1_hooks" ],
    [ "Maps", "namespace_hamstar_helpers_1_1_services_1_1_maps.html", "namespace_hamstar_helpers_1_1_services_1_1_maps" ],
    [ "Messages", "namespace_hamstar_helpers_1_1_services_1_1_messages.html", "namespace_hamstar_helpers_1_1_services_1_1_messages" ],
    [ "ModCompatibilities", "namespace_hamstar_helpers_1_1_services_1_1_mod_compatibilities.html", "namespace_hamstar_helpers_1_1_services_1_1_mod_compatibilities" ],
    [ "ModHelpers", "namespace_hamstar_helpers_1_1_services_1_1_mod_helpers.html", "namespace_hamstar_helpers_1_1_services_1_1_mod_helpers" ],
    [ "ModTagDefinitions", "namespace_hamstar_helpers_1_1_services_1_1_mod_tag_definitions.html", "namespace_hamstar_helpers_1_1_services_1_1_mod_tag_definitions" ],
    [ "Network", "namespace_hamstar_helpers_1_1_services_1_1_network.html", "namespace_hamstar_helpers_1_1_services_1_1_network" ],
    [ "OverlaySounds", "namespace_hamstar_helpers_1_1_services_1_1_overlay_sounds.html", "namespace_hamstar_helpers_1_1_services_1_1_overlay_sounds" ],
    [ "RecipeHack", "namespace_hamstar_helpers_1_1_services_1_1_recipe_hack.html", "namespace_hamstar_helpers_1_1_services_1_1_recipe_hack" ],
    [ "Timers", "namespace_hamstar_helpers_1_1_services_1_1_timers.html", "namespace_hamstar_helpers_1_1_services_1_1_timers" ],
    [ "TML", "namespace_hamstar_helpers_1_1_services_1_1_t_m_l.html", "namespace_hamstar_helpers_1_1_services_1_1_t_m_l" ],
    [ "UI", "namespace_hamstar_helpers_1_1_services_1_1_u_i.html", "namespace_hamstar_helpers_1_1_services_1_1_u_i" ]
];