var namespace_hamstar_helpers_1_1_services_1_1_mod_compatibilities =
[
    [ "ExtensibleInventoryCompat", "namespace_hamstar_helpers_1_1_services_1_1_mod_compatibilities_1_1_extensible_inventory_compat.html", "namespace_hamstar_helpers_1_1_services_1_1_mod_compatibilities_1_1_extensible_inventory_compat" ]
];