var namespace_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_attributes =
[
    [ "ProjectileAttributeHelpers", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_attributes_1_1_projectile_attribute_helpers.html", "class_hamstar_helpers_1_1_helpers_1_1_projectiles_1_1_attributes_1_1_projectile_attribute_helpers" ]
];