var namespace_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions =
[
    [ "ItemGroupIDs", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions_1_1_item_group_i_ds.html", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions_1_1_item_group_i_ds" ],
    [ "NPCGroupIDs", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions_1_1_n_p_c_group_i_ds.html", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions_1_1_n_p_c_group_i_ds" ],
    [ "ProjectileGroupIDs", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions_1_1_projectile_group_i_ds.html", "class_hamstar_helpers_1_1_services_1_1_entity_groups_1_1_definitions_1_1_projectile_group_i_ds" ]
];