var namespace_hamstar_helpers_1_1_services_1_1_debug_1_1_custom_hotkeys =
[
    [ "CustomHotkeys", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_custom_hotkeys_1_1_custom_hotkeys.html", "class_hamstar_helpers_1_1_services_1_1_debug_1_1_custom_hotkeys_1_1_custom_hotkeys" ]
];