var namespace_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_formatting =
[
    [ "StringFormattingHelpers", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_formatting_1_1_string_formatting_helpers.html", "class_hamstar_helpers_1_1_helpers_1_1_dot_n_e_t_1_1_formatting_1_1_string_formatting_helpers" ]
];