using HamstarHelpers.Helpers.DebugHelpers;
using System.Collections.Generic;


namespace HamstarHelpers.Internals.ModTags {
	abstract partial class TagsMenuContextBase {
		public static IDictionary<string, string> Tags = new Dictionary<string, string> {
			{ "Core Game",				"Mechanics: Adds a \"bullet hell\" mode, adds a stamina bar, removes mining, etc." },
			{ "Combat",					"Mechanics: Adds weapon reloading, dual-wielding, changes mob behaviors, etc." },
			{ "Movement",				"Mechanics: Gives super speed, adds dodging mechanics, adds unlimited flight, etc." },
			{ "Mining",					"Mechanics: Adds new types of mining tools or makes specific types of excavation faster." },
			{ "Building",				"Mechanics: Enables placing prefabs, provides measuring tools, adds abilities for editing world, etc." },
			{ "Traveling",				"Mechanics: Adds fast travel options, adds new minecarts, rewards for distance traveled, etc." },
			{ "Creativity",             "Adds decorative items, enables changing scenery or colors, adds tools for abstract constructrs, etc." },
			{ "Quests",                 "Adds goals for player to progress or profit from." },
			{ "Game Mode(s)",           "New game rules; added end goals, progression, setting, session, etc." },
			{ "Story or Lore",          "Implements elements of story telling or universe lore." },
			{ "Player Class(es)",       "Adds new player 'classes', usually via. custom damage types or special forms of attack/defense." },
			{ "Player Stats",           "Modifies player attack, defense, and other intrinsic elements." },
			{ "NPC Stats",              "Modifies NPC attack, defense, and other intrinsic elements." },
			{ "NPC Behavior",           "Modifies NPC AIs for new or tweaked behaviors." },
			{ "Informational",          "Adds informational items (time, weather, etc.), reports game statistics, gives specific information, etc." },
			{ "Specialized",            "Focuses on one main specific, well-defined function." },
			{ "Replacements",           "Primarily meant as an alternative to something the game already provides." },
			//{ "Visuals",                "Implements new or improved sprites, adds new background details, etc." },
			{ "Special FX",             "Adds gore effects, adds motion blurs, improves particle effects, etc." },
			{ "Affects World",          "Generates new set pieces, alters biome shapes, populates areas with new types of growth, etc." },
			{ "Esoteric",               "Does something uncommon or unexpected." },
			{ "Challenge",              "Increases difficulty of something, e.g. for player bragging rights." },
			{ "Nerfs",                  "Decreases difficulty of something, e.g. to make beating bosses easier." },
			{ "Adds Convenience",       "Reduces annoyances; adds auto-reactivating buffs, auto-trashes junk items, centralizes chests, etc." },
			{ "Vanilla Balanced",       "Balanced around plain Terraria; progress will not happen faster than usual." },
			{ "Loosely Balanced",       "Little concern for affect on progress; may enable Vanilla sequence breaks." },
			{ "Cheat-like",             "Significantly reduces or removes some game challenges completely; may be 'unfair'." },
			{ "Multiplayer Compat.",	"Built for multiplayer." },
			{ "PvP",                    "Player vs player." },
			{ "Coop",                   "Requires or involves direct player cooperation." },
			{ "Teams",                  "Requires or involves teams of players." },
			{ "Music",					"Content: Adds new music." },
			{ "Rich Art",				"Content: Adds extensive or detailed art for new or existing game entities." },
			{ "Sounds",					"Content: Adds new sound effects or ambience." },
			{ "Item Sets",				"Content: Adds discrete (often themed) sets of items." },
			{ "Weapons",				"Content: Adds new weapons." },
			{ "Hostile NPCs",			"Content: Adds new hostile NPCs (monsters)." },
			{ "Town NPCs",				"Content: Adds new town NPCs (villagers)." },
			{ "Critters",				"Content: Adds (passive) biome fauna." },
			{ "Bosses",					"Content: Adds new boss monsters." },
			{ "Invasions",				"Content: Adds new invasion events." },
			{ "Blocks",					"Content: Adds new block types." },
			{ "Wiring",					"Content: Adds tools and toys for use for wiring." },
			{ "Decorative",				"Content: Adds decorative objects (e.g. furniture for houses)." },
			{ "Fishing",				"Content: Adds tools or mechanics for fishing." },
			{ "Buffs & Pots.",			"Content: Adds new buffs and potions." },
			{ "Accessories",			"Content: Adds new player accessories." },
			{ "Biomes",					"Content: Adds new world biomes." },
			{ "Vanity",					"Content: Adds new player vanity items or options." },
			{ "Ores",					"Content: Adds mineable ores (and probably matching equipment tiers)." },
			{ "Dark",					"Theme: Gloomy, edgy, or just plain poor visibility." },
			{ "Silly",					"Theme: Light-hearted, immersion-breaking, or just plain absurd." },
			{ "Fantasy",				"Theme: Elements of ancient mythologies, swords & sorcery, and maybe a hobbit or 2." },
			{ "Medieval",				"Theme: Chivalry, castles, primitive technology, melee fighting, archery, etc." },
			{ "Military",				"Theme: Guns and stuff." },
			{ "Nature",					"Theme: Birds, bees, rocks, trees, etc." },
			{ "Sci-Fi",					"Theme: Robots, lasers, flying machines, etc." },
			//{ "Mixed",				"Theme: Mashup of genres, but not purely in a silly way." },
			//{ "Where: Surface",         "" },
			//{ "Where: Underground",		"" },
			//{ "Where: Ocean",			"" },
			//{ "Where: Dungeon",			"" },
			//{ "Where: Jungle",			"" },
			//{ "Where: Hell",			"" },
			//{ "Where: Evil Biome",		"" },
			//{ "Where: Hallow Biome",	"" },
			{ "When: Pre-Hard Mode",	"" },
			{ "When: Hard Mode",		"" },
			{ "When: Post-Plantera",	"" },
			{ "When: Post-Moonlord",	"" },
			{ "Open Source",			"" },
			//{ "Made By Team",			"" },
			{ "Unmaintained",			"" },
			{ "Unfinished",				"" },
			{ "Non-functional",			"" },
			//{ "Simplistic",			"" }
			{ "Buggy",					"" },
			//{ "Minimalistic",			"" },
			//{ "Shows Effort",			"" },
			//{ "Polished",				"" }
		};
	}
}
